name: recycle_view
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  camera: ^0.10.5+3
  camera_camera: ^3.0.0
  cloud_firestore: ^4.8.4
  firebase_auth: ^4.7.1
  firebase_core: ^2.15.0
  firebase_storage: ^11.2.5
  flutter:
    sdk: flutter
  #flutter_map: ^3.1.0
  get: ^4.6.5
  google_fonts: 
  google_sign_in: ^6.1.4
  graphic: ^2.2.0
  image_picker: ^1.0.2
  mask_text_input_formatter: ^2.5.0
  open_street_map_search_and_pick: ^0.1.0
  page_transition: ^2.0.9
  permission_handler: ^10.4.3
  provider: ^6.0.5
  shelf: ^1.4.1
  #tflite: ^1.1.2
  syncfusion_flutter_charts: ^22.1.39
  tflite_flutter: ^0.10.1
  tflite_v2: ^1.0.0
  #tflite_flutter: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icons/logo.png"

flutter:
  assets:
    - assets/ia/model_unquant.tflite
    - assets/ia/labels.txt
    - assets/images/
    - assets/images/background/
    - assets/images/icons/
    - assets/images/icons_materials/
    
  uses-material-design: true
