name: recycle_view
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  cloud_firestore: ^4.8.4
  firebase_auth: ^4.7.1
  firebase_core: ^2.15.0
  firebase_storage: ^11.2.5
  flutter:
    sdk: flutter
  google_fonts: ^5.1.0
  google_sign_in: ^6.1.4
  graphic: ^2.2.0
  http: ^1.1.0
  image_picker: ^1.0.2
  mask_text_input_formatter: ^2.5.0
  page_transition: ^2.0.9
  provider: ^6.0.5
  shelf: ^1.4.1
  syncfusion_flutter_charts: ^22.1.39

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
    - assets/images/background/
    - assets/images/icons/
    
  uses-material-design: true
